version: '3'

volumes:
  data:

services:
  nextcloud:
    image: nextcloud:23.0
    container_name: nextcloud
    restart: unless-stopped
    depends_on: 
      - mariadb
    ports:
      - 80:80
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      NEXTCLOUD_ADMIN_USER: $ADMIN_USER
      NEXTCLOUD_ADMIN_PASSWORD: $ADMIN_PASSWORD
  
  mariadb:
    image: mariadb:10.10
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: r00tP@ssw0rd
      MARIADB_DATABASE: $DB_DATABASE
      MARIADB_USER: $DB_USER
      MARIADB_PASSWORD: $DB_PASSWORD

