version: '3'

networks:
  laravel:

services:
  nginx:
    depends_on:
      - php
      - mariadb
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  mariadb:
    container_name: mariadb
    restart: unless-stopped
    image: mariadb:10.9.3
    tty: true
    ports:
      - 4306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: r00tP@ssw0rd
      MARIADB_DATABASE: laraveldb
      MARIADB_USER: laraveldbuser
      MARIADB_PASSWORD: P@ssw0rd
    networks:
      - laravel
  
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000
    networks:
      - laravel

  composer:
    image: composer:2.4.4
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  npm:
    image: node:18.12-alpine
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - laravel


volumes:
  data:
