version: '3'

networks:
  laravel:

services:
  nginx:
    depends_on:
      - php
      - mariadb
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  mariadb:
    container_name: mariadb
    restart: unless-stopped
    image: mariadb:10.9.3
    tty: true
    ports:
      - 4306:3306
    volumes:
      - data:/var/lib/mysql

    environment:
      MARIADB_ROOT_PASSWORD: r00tP@ssw0rd
      MARIADB_DATABASE: laraveldb
      MARIADB_USER: laraveldbuser
      MARIADB_PASSWORD: P@ssw0rd
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000
    networks:
      - laravel


volumes:
  data:
